# Inspired by https://searchfox.org/firefox-main/source/toolkit/components/normandy/components.conf

Classes = [
    {
        'cid': '{b3ac3a21-fb4b-4013-9bcb-bbb4ae1ea861}',
        'contract_ids': ['@mozilla.org/network/protocol/about;1?what=policies'],
        'esModule': 'resource://gre/modules/BrowserTVAboutPages.sys.mjs',
        'constructor': 'AboutPolicies',
    },
    {
        'cid': '{057bb874-aabf-4b9a-a43e-3440c3e4bfa2}',
        'contract_ids': ['@mozilla.org/network/protocol/about;1?what=robots'],
        'esModule': 'resource://gre/modules/BrowserTVAboutPages.sys.mjs',
        'constructor': 'AboutRobots',
    },
]
